// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt;

import java.awt.image.AffineTransformOp;

public enum AffineTransformType {
	TYPE_NEAREST_NEIGHBOR, TYPE_BILINEAR;


}
