// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
package net.sourceforge.plantuml.klimt.font;

import net.sourceforge.plantuml.klimt.geom.XDimension2D;

public interface StringBounder {


	public boolean matchesProperty(String propertyName);

}
